### ISSUE TITLE
Application Request: Monitor 

### ISSUE THREAD

**Issue by amz-x** [decathorpe/elementary-appcenter-rpms#3]
Request to add process [monitor application](https://github.com/stsdc/monitor) to repository. 

Latest COPR build status:
https://copr.fedorainfracloud.org/coprs/amz/extras/build/1081661/

Spec:
https://github.com/amz-x/extras/blob/master/specs/elementary-monitor/elementary-monitor.spec

Personally, it would make more sense to maintain it here.

**Comment by decathorpe** [comment]
Done! Thanks for the link to the working .spec file. I've renamed the package to "monitor" though, since it's not an official elementary package (and the name wasn't taken yet).

https://copr.fedorainfracloud.org/coprs/decathorpe/elementary-appcenter/package/monitor/

I'll try to keep it up to date, like the other apps.

**Comment by amz-x** [comment]
Awesome! Thank you.
